### ISSUE TITLE
unexpected smask type <</Type /Mask/S /Luminosity/G 13 0 R>>

### ISSUE THREAD

**Issue by victorinno** [jrmuizel/pdf-extract#24]
Hi there, I'm trying to use this library to read a pdf, but for some reason it just doesn't work because of this mask.

Here ir the following error:

thread 'main' panicked at 'unexpected smask type <</Type /Mask/S /Luminosity/G 13 0 R>>', \.cargo\registry\src\github.com-1ecc6299db9ec823\pdf-extract-0.6.2\src\lib.rs:1190:24
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at \.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libcore\fmt\mod.rs:1076
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\io\mod.rs:1537
   5: std::sys_common::backtrace::_print
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:486
  10: std::panicking::begin_panic_handler
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:388
  11: std::panicking::begin_panic_fmt
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:342
  12: pdf_extract::apply_state
             at C:\Users\rotc_\.cargo\registry\src\github.com-1ecc6299db9ec823\pdf-extract-0.6.2\src\lib.rs:1190
  13: pdf_extract::Processor::process_stream
             at C:\Users\rotc_\.cargo\registry\src\github.com-1ecc6299db9ec823\pdf-extract-0.6.2\src\lib.rs:1561
  14: pdf_extract::output_doc
             at C:\Users\rotc_\.cargo\registry\src\github.com-1ecc6299db9ec823\pdf-extract-0.6.2\src\lib.rs:2028
  15: pdf_extract::extract_text<std::path::PathBuf*>
             at C:\Users\rotc_\.cargo\registry\src\github.com-1ecc6299db9ec823\pdf-extract-0.6.2\src\lib.rs:1989
  16: contador_palavras::read_pdf
             at .\src\main.rs:32
  17: contador_palavras::main
             at .\src\main.rs:53
  18: std::rt::lang_start::{{closure}}<core::result::Result<(), exitfailure::ExitFailure>>
             at C:\Users\rotc_\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  19: std::rt::lang_start_internal::{{closure}}
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\rt.rs:52
  20: std::panicking::try::do_call
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:297
  21: std::panicking::try
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:274
  22: std::panic::catch_unwind
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panic.rs:394
  23: std::rt::lang_start_internal
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\rt.rs:51
  24: std::rt::lang_start<core::result::Result<(), exitfailure::ExitFailure>>
             at  \.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  25: main
  26: invoke_main
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  27: __scrt_common_main_seh
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  28: BaseThreadInitThunk
  29: RtlUserThreadStart

**Comment by jrmuizel** [comment]
Do you still see this? Can you share the pdf?
