### ISSUE TITLE
Pack of files which cause crashes

### ISSUE THREAD

**Issue by qarmin** [jrmuizel/pdf-extract#96]
Version f456267677dc0af2dccfee40cd505bfef4bf56d6 

Code taken from example

Example crashes
```
thread 'main' panicked at /home/runner/.cargo/git/checkouts/pdf-extract-1e3ad5dc34c14d18/f456267/src/lib.rs:203:30:
F1
```
```
thread 'main' panicked at /home/runner/.cargo/git/checkouts/pdf-extract-1e3ad5dc34c14d18/f456267/src/lib.rs:203:69:
wrong type
```
```
thread 'main' panicked at /home/runner/.cargo/git/checkouts/pdf-extract-1e3ad5dc34c14d18/f456267/src/lib.rs:775:75:
missing unicode map and encoding
```
```
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/type1-encoding-parser-0.1.0/src/lib.rs:169:31:
failed to parse: Mismatch { message: "expect repeat at least 1 times, found 0 times", position: 0 }
```
```
thread 'main' panicked at /home/runner/.cargo/git/checkouts/pdf-extract-1e3ad5dc34c14d18/f456267/src/lib.rs:176:52:
missing object reference: ObjectNotFound
```
```
thread 'main' panicked at /home/runner/.cargo/git/checkouts/pdf-extract-1e3ad5dc34c14d18/f456267/src/lib.rs:1266:21:
assertion `left == right` failed
  left: [69, 120, 116, 71, 82, 116, 97, 116, 101]
 right: [69, 120, 116, 71, 83, 116, 97, 116, 101]
```
```
thread 'main' panicked at /home/runner/.cargo/git/checkouts/pdf-extract-1e3ad5dc34c14d18/f456267/src/lib.rs:1710:113:
index out of bounds: the len is 1 but the index is 1
```
```
thread 'main' panicked at /home/runner/.cargo/git/checkouts/pdf-extract-1e3ad5dc34c14d18/f456267/src/lib.rs:2230:78:
MediaBox
```
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==253329==ERROR: AddressSanitizer: stack-overflow on address 0x7ffc379d6fe0 (pc 0x56468bb7fa5a bp 0x7ffc379d7250 sp 0x7ffc379d6fe0 T0)
    #0 0x56468bb7fa5a in _$LT$$LP$A$C$B$RP$$u20$as$u20$nom..branch..Alt$LT$Input$C$Output$C$Error$GT$$GT$::choice::hf86541610e53f9a3 /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nom-7.1.3/src/branch/mod.rs:134
    #1 0x56468bb8677f in nom::branch::alt::_$u7b$$u7b$closure$u7d$$u7d$::hf0241fec7440fc5f /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nom-7.1.3/src/branch/mod.rs:50:15
    #2 0x56468bb8677f in lopdf::parser::boolean::h0c61e83af7618843 /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lopdf-0.32.0/src/nom_parser.rs:245:5
    #3 0x56468bb8677f in core::ops::function::FnMut::call_mut::h0f9c39e3136131d3 /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/ops/function.rs:166:5
    #4 0x56468bb8677f in _$LT$F$u20$as$u20$nom..internal..Parser$LT$I$C$O$C$E$GT$$GT$::parse::hee245dee6a85e09d /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nom-7.1.3/src/internal.rs:325:5
    #5 0x56468bb8677f in _$LT$$LP$A$C$B$C$C$C$D$C$E$C$F$C$G$C$H$C$I$C$J$RP$$u20$as$u20$nom..branch..Alt$LT$Input$C$Output$C$Error$GT$$GT$::choice::hf20b9bdb7f845f39 /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nom-7.1.3/src/branch/mod.rs:146:11
    #6 0x56468bb8677f in nom::branch::alt::_$u7b$$u7b$closure$u7d$$u7d$::hd14b167dc8b1c8db /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nom-7.1.3/src/branch/mod.rs:50:15
    #7 0x56468bb8677f in lopdf::parser::_direct_objects::h10a60b13670fd2bc /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lopdf-0.32.0/src/nom_parser.rs:308:5
    #8 0x56468bb8677f in core::ops::function::FnMut::call_mut::h16de2db6ef0fa4b6 /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/ops/function.rs:166:5
    #9 0x56468bb8677f in _$LT$F$u20$as$u20$nom..internal..Parser$LT$I$C$O$C$E$GT$$GT$::parse::h9502e184d7436f60 /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nom-7.1.3/src/internal.rs:325:5
    #10 0x56468bb8b3da in nom::sequence::terminated::_$u7b$$u7b$closure$u7d$$u7d$::ha6a8bb03d245f50f /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nom-7.1.3/src/sequence/mod.rs:106:23
```

Files pack - [REPORTS___PDF_EXTRACT_4.zip](https://github.com/user-attachments/files/17179719/REPORTS___PDF_EXTRACT_4.zip)

**Comment by jrmuizel** [comment]
Where do these PDFs come from? They seems somewhat broken.

**Comment by qarmin** [comment]
I threw several valid pdf's into the fuzzer to create versions of them that crash this library, so it is expected that they may be broken
